package yakasov.japaneselettergame;

import android.os.Bundle;
import android.view.MenuItem;
import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AppCompatActivity;
import androidx.preference.PreferenceFragmentCompat;

/**
 * SettingsActivity class defines the GUI and all related code for the settings
 * screen. All methods defined here directly affect GUI elements. Any method
 * that does not affect the GUI is placed in BackCode.
 *
 * <p>Settings are handled in this activity. This activity is accessible from
 * MainActivity
 * using the toolbar.
 */
public final class SettingsActivity extends AppCompatActivity {

  @Override
  protected void onCreate(final Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.settings_activity);
    if (savedInstanceState == null) {
      getSupportFragmentManager()
          .beginTransaction()
          .replace(R.id.settings, new SettingsFragment())
          .commit();
    }
    ActionBar actionBar = getSupportActionBar();
    if (actionBar != null) {
      actionBar.setDisplayHomeAsUpEnabled(true);
    }
  }

  @Override // Link back arrow to onBackPressed
  public boolean onOptionsItemSelected(final MenuItem item) {
    if (item.getItemId() == android.R.id.home) {
      onBackPressed();
    }
    return super.onOptionsItemSelected(item);
  }

  @Override
  public void onBackPressed() {
    finish();
  }

  /**
   * Generated by Android Studio upon creating an activity using Preference
   * objects. Loads saved preferences from internal storage.
   */
  public static final class SettingsFragment extends PreferenceFragmentCompat {
    @Override
    public void onCreatePreferences(
        final Bundle savedInstanceState, final String rootKey) {
      setPreferencesFromResource(R.xml.root_preferences, rootKey);
    }
  }
}
